/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Text,
  'manufacturer' : IDL.Text,
  'distributorContact' : IDL.Text,
  'distributorCountry' : IDL.Text,
  'name' : IDL.Text,
  'distributorName' : IDL.Text,
  'productionDate' : IDL.Text,
  'currentOwner' : IDL.Text,
  'serialNumber' : IDL.Text,
  'batchNumber' : IDL.Text,
  'distributorAddress' : IDL.Text,
  'warrantyInfo' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const VerificationLog = IDL.Record({
  'resultStatus' : IDL.Text,
  'productSearched' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const VerificationResult = IDL.Record({
  'status' : IDL.Text,
  'matchedProductDetails' : IDL.Opt(Product),
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationHistory' : IDL.Func(
      [],
      [IDL.Vec(VerificationLog)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'recordVerification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerProduct' : IDL.Func([Product], [], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'verifyProduct' : IDL.Func([IDL.Text], [VerificationResult], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'manufacturer' : IDL.Text,
    'distributorContact' : IDL.Text,
    'distributorCountry' : IDL.Text,
    'name' : IDL.Text,
    'distributorName' : IDL.Text,
    'productionDate' : IDL.Text,
    'currentOwner' : IDL.Text,
    'serialNumber' : IDL.Text,
    'batchNumber' : IDL.Text,
    'distributorAddress' : IDL.Text,
    'warrantyInfo' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const VerificationLog = IDL.Record({
    'resultStatus' : IDL.Text,
    'productSearched' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const VerificationResult = IDL.Record({
    'status' : IDL.Text,
    'matchedProductDetails' : IDL.Opt(Product),
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationHistory' : IDL.Func(
        [],
        [IDL.Vec(VerificationLog)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'recordVerification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerProduct' : IDL.Func([Product], [], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'verifyProduct' : IDL.Func([IDL.Text], [VerificationResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };